create table public.bot_lab_test_assertions(label text);
create function public.lab_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'ASSERTION: %',label; end if; insert into public.bot_lab_test_assertions values(label); end;$$;
create function public.lab_expect_error(sql_text text,wanted text,label text) returns void language plpgsql as $$declare caught text;begin begin execute sql_text; exception when others then caught:=sqlerrm;end;perform public.lab_assert(caught like wanted||'%',label);end;$$;
select public.lab_expect_error($q$select public.bot_lab_admin_internal(repeat('b',64),'access')$q$,'ADMIN_REQUIRED','display-name impersonation denied');
select public.lab_expect_error($q$select public.bot_lab_admin_internal(repeat('c',64),'access')$q$,'ADMIN_REQUIRED','expired real-admin session denied');
select public.lab_expect_error($q$select public.bot_lab_admin_internal(repeat('d',64),'access')$q$,'ADMIN_REQUIRED','invalid session denied');
select public.lab_assert((public.bot_lab_admin_internal(repeat('a',64),'access')->>'allowed')::boolean,'active immutable admin authorized');
select public.lab_assert(not has_function_privilege('anon','public.bot_lab_admin_internal(text,text,jsonb)','EXECUTE'),'anon RPC revoked');
select public.lab_assert(not has_function_privilege('authenticated','public.claim_bot_lab_internal(uuid)','EXECUTE'),'authenticated worker RPC revoked');
select public.lab_assert(not has_table_privilege('service_role','private.bot_lab_jobs','SELECT'),'service direct table access revoked');
select public.lab_assert(not has_table_privilege('anon','private.bot_lab_results','SELECT'),'anon hidden simulation records revoked');
select public.lab_expect_error($q$select public.bot_lab_admin_internal(repeat('a',64),'create','{"requestId":"10000000-0000-4000-8000-000000000001","config":{"games":10,"seed":42,"ruleset":"popular","compare":false,"lineup":null}}')$q$,'WORKER_NOT_CONFIGURED','disabled worker does not create fake queued progress');
update private.bot_lab_scheduler_config set enabled=true;
select public.lab_expect_error($q$update private.bot_lab_scheduler_config set endpoint_url='https://other-project.supabase.co/functions/v1/bot-lab-worker'$q$,'new row for relation','wrong project endpoint forbidden');
select public.lab_expect_error($q$select public.bot_lab_admin_internal(repeat('a',64),'create','{"requestId":"10000000-0000-4000-8000-000000000001","config":{"games":5001,"seed":42,"ruleset":"popular","compare":false,"lineup":null}}')$q$,'INVALID_CONFIG','resource bound enforced');
select public.lab_expect_error($q$select public.bot_lab_admin_internal(repeat('a',64),'create','{"requestId":"10000000-0000-4000-8000-000000000001","config":{"games":10,"seed":42,"ruleset":"popular","compare":false,"lineup":[null,null,null,null]}}')$q$,'INVALID_CONFIG','null lineup tier rejected');
do $$declare j jsonb; again jsonb; c jsonb; c2 jsonb; token uuid; idx integer; cp jsonb;begin
 j:=public.bot_lab_admin_internal(repeat('a',64),'create','{"requestId":"10000000-0000-4000-8000-000000000001","config":{"games":10,"seed":42,"ruleset":"popular","compare":false,"lineup":null}}');
 again:=public.bot_lab_admin_internal(repeat('a',64),'create','{"requestId":"10000000-0000-4000-8000-000000000001","config":{"games":10,"seed":42,"ruleset":"popular","compare":false,"lineup":null}}');
 perform public.lab_assert(j->>'id'=again->>'id','create retry returns same durable job');
 perform public.lab_assert(not(j ? 'checkpoint') and not(j ? 'lease_token'),'admin progress excludes canonical hands and tokens');
 perform public.lab_assert((select count(*)=1 from net.test_outbox),'transaction dispatch issued once');
 token:=(select i.token from private.bot_lab_invocations i limit 1);
 c:=public.claim_bot_lab_internal(token);
 perform public.lab_assert(c->>'status'='running' and (c->>'started_games')::integer=1,'real worker claimed game once');
 perform public.lab_expect_error('select public.claim_bot_lab_internal('||quote_literal(token)||'::uuid)','INVALID_WORKER_TOKEN','one-time worker token cannot replay');
 cp:='{"schema":1,"state":{"gameId":"00000000-0000-4000-8000-00000000b001","progression":{"dealNumber":2}},"steps":32}';
 perform public.lab_assert(public.commit_bot_lab_chunk_internal((c->>'id')::uuid,(c->>'lease_token')::uuid,0,cp,null),'checkpoint commits under lease');
 perform public.lab_assert(not public.commit_bot_lab_chunk_internal((c->>'id')::uuid,(c->>'lease_token')::uuid,0,cp,null),'duplicate chunk fenced');
 c2:=public.claim_bot_lab_internal((select i.token from private.bot_lab_invocations i limit 1));
 perform public.lab_assert(c2->'checkpoint'=cp and (c2->>'started_games')::integer=1,'new invocation resumes existing checkpoint without duplicate start');
 update private.bot_lab_jobs set lease_until=clock_timestamp()-interval '1 second' where id=(c2->>'id')::uuid;
 perform private.dispatch_bot_lab_internal();
 c:=public.claim_bot_lab_internal((select i.token from private.bot_lab_invocations i limit 1));
 perform public.lab_assert((c->>'recoveries')::integer=1,'expired worker lease recovers');
 perform public.lab_assert(not public.commit_bot_lab_chunk_internal((c2->>'id')::uuid,(c2->>'lease_token')::uuid,0,cp,null),'old worker cannot overwrite recovered lease');
 j:=public.bot_lab_admin_internal(repeat('a',64),'cancel',jsonb_build_object('jobId',c->>'id'));
 perform public.lab_assert(j->>'status'='cancelled','admin cancellation is immediate and durable');
 perform public.lab_assert(not public.commit_bot_lab_chunk_internal((c->>'id')::uuid,(c->>'lease_token')::uuid,0,cp,null),'cancelled in-flight chunk cannot commit or revive job');
 perform public.lab_assert(private.dispatch_bot_lab_internal() is null,'terminal job stops scheduling');
 again:=public.bot_lab_admin_internal(repeat('a',64),'cancel',jsonb_build_object('jobId',c->>'id'));
 perform public.lab_assert(again->>'status'='cancelled','cancel retry idempotent');
end;$$;
select public.lab_expect_error($q$select public.bot_lab_admin_internal(repeat('a',64),'create','{"requestId":"10000000-0000-4000-8000-000000000001","config":{"games":100,"seed":42,"ruleset":"popular","compare":false,"lineup":null}}')$q$,'ACTION_ID_CONFLICT','request ID cannot change configuration');
-- Test successful commit exactly once and a canonical rejection persisted as failure.
do $$declare j jsonb; c jsonb; r jsonb;begin
 j:=public.bot_lab_admin_internal(repeat('a',64),'create','{"requestId":"10000000-0000-4000-8000-000000000002","config":{"games":10,"seed":42,"ruleset":"popular","compare":true,"lineup":null}}');
 perform public.lab_assert((j->>'total_games')::integer=20,'comparison has two real games per logical sample');
 perform public.lab_expect_error($q$select public.bot_lab_admin_internal(repeat('a',64),'create','{"requestId":"10000000-0000-4000-8000-000000000003","config":{"games":10,"seed":42,"ruleset":"popular","compare":false,"lineup":null}}')$q$,'duplicate key value','global single active job enforced');
 c:=public.claim_bot_lab_internal((select i.token from private.bot_lab_invocations i limit 1));
 r:='{"config":{"ruleset":"popular"},"scores":[1,2,3,4],"metrics":[{},{},{},{}]}';
 perform public.lab_assert(public.commit_bot_lab_chunk_internal((c->>'id')::uuid,(c->>'lease_token')::uuid,0,null,r),'result commit');
 perform public.lab_assert(not public.commit_bot_lab_chunk_internal((c->>'id')::uuid,(c->>'lease_token')::uuid,0,null,r),'duplicate result prevented');
 perform public.lab_assert((select count(*)=1 from private.bot_lab_results where job_id=(c->>'id')::uuid),'unique game index');
 c:=public.claim_bot_lab_internal((select i.token from private.bot_lab_invocations i limit 1));
 perform public.lab_assert(public.commit_bot_lab_chunk_internal((c->>'id')::uuid,(c->>'lease_token')::uuid,1,null,null,'REJECTED_ACTION'),'real error recorded');
 j:=public.bot_lab_admin_internal(repeat('a',64),'get',jsonb_build_object('jobId',c->>'id'));
 perform public.lab_assert(j->>'status'='failed' and (j->>'errors')::integer=1 and (j->>'rejected_actions')::integer=1 and (j->>'completed_games')::integer=1,'failed starts are not fake successes or silently dropped');
 perform public.lab_assert(exists(select 1 from jsonb_array_elements(public.bot_lab_admin_internal(repeat('a',64),'list')->'jobs') x where x->>'id'=j->>'id'),'history survives browser and worker closure');
end;$$;
select count(*) as passed_database_assertions from public.bot_lab_test_assertions;select public.lab_expect_error($q$select public.bot_lab_stats_internal(repeat('b',64),'10000000-0000-4000-8000-000000000001')$q$,'ADMIN_REQUIRED','stats also require immutable admin identity');
select public.lab_assert(not has_function_privilege('anon','public.bot_lab_stats_internal(text,uuid)','EXECUTE'),'stats RPC not anon exposed');
